version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'FISA_hcajbjaibh672983'
      MYSQL_DATABASE: 'bd_django'
      MYSQL_USER: 'FISA_user_bd'
      MYSQL_PASSWORD: 'FISA_Link_corentin789'
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      fisa_network:
        ipv4_address: 172.255.0.4

  django_web:
    build:
      context: ./FISA_Link_website
      dockerfile: Dockerfile_front
    container_name: django_web
    depends_on:
      - db
    networks:
      fisa_network:
        ipv4_address: 172.255.0.100

  django_api:
    build:
      context: ./FISA_Link_website
      dockerfile: Dockerfile_api
    container_name: django_api
    depends_on:
      - db
    networks:
      fisa_network:
        ipv4_address: 172.255.0.101

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django_web
      - django_api
    networks:
      fisa_network:
        ipv4_address: 172.255.0.200

volumes:
  mariadb_data:
    driver: local

networks:
  fisa_network:
    ipam:
      driver: default
      config:
        - subnet: 172.255.0.0/24
