services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'FISA_hcajbjaibh672983'
      MYSQL_DATABASE: 'bd_django'
      MYSQL_USER: 'FISA_user_bd'
      MYSQL_PASSWORD: 'FISA_Link_corentin789'
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      fisa_network:
        ipv4_address: 172.255.0.4

volumes:
  mariadb_data:
    driver: local

networks:
  fisa_network:
    ipam:
      driver: default
      config:
        - subnet: 172.255.0.0/24
