# Dockerfile_front
FROM python:3.11-bullseye

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers du projet dans le conteneur
COPY . /app

# Installer les dépendances
RUN pip install --upgrade pip \
    && chmod +x /app/run_web.sh

# Exposer le port 8800 pour le service web
EXPOSE 8800

# Commande par défaut
CMD ["/app/run_web.sh"]
